version: '3'

services:
    nginx:
        image: nginx
        depends_on: [influxdb,chronograf]
        volumes:
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./.htpasswd:/etc/nginx/conf.d/.htpasswd"
            - "./data/letsencrypt/certs:/etc/letsencrypt"
            - "./data/letsencrypt/certs-data:/data/letsencrypt"
        ports:
            - 80:80
            - 8080:8080
            - 8080:8443
            - 443:443
        environment:
            - NGINX_HOST=localhost
        restart: always
        command: /bin/bash -c "nginx -g 'daemon off;'"
        networks:
          - influxdb
    influxdb:
        image: influxdb
        restart: always
        volumes:
          - ./data/influxdb:/var/lib/influxdb
        networks:
          - influxdb
    kapacitor:
        image: kapacitor
        depends_on: [influxdb]
        restart: always
        environment:
          KAPACITOR_HOSTNAME: kapacitor
          KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        volumes:
          - ./data/kapcitor:/var/lib/kapacitor
        networks:
          - influxdb
    chronograf:
        image: chronograf
        depends_on: [influxdb,kapacitor]
        restart: always
        volumes:
          - ./data/chronograf:/var/lib/chronograf
        networks:
          - influxdb
        command:
          - chronograf
          - --influxdb-url=http://influxdb:8086
    telegraf:
      image: telegraf
      hostname: telegraf
      depends_on: [influxdb,nginx]
      restart: always
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/rootfs/sys:ro
        - /proc:/rootfs/proc:ro
        - /etc:/rootfs/etc:ro
      depends_on: [influxdb]
      environment:
        HOST_PROC: /rootfs/proc
        HOST_SYS: /rootfs/sys
        HOST_ETC: /rootfs/etc
      networks:
          - influxdb

networks:
    influxdb: