version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        depends_on: [influxdb,chronograf]
        volumes:
            - "./data/vhost:/etc/nginx/vhost.d"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./.htpasswd:/etc/nginx/conf.d/.htpasswd"
            - "./data/html:/usr/share/nginx/html"
            - "./data/letsencrypt/certs:/etc/nginx/certs:ro"
        ports:
            - 80:80
            - 8080:8080
            - 8443:8443
            - 443:443
        environment:
            - NGINX_HOST=telemetry.functn.com
        restart: always
        command: /bin/bash -c "nginx -g 'daemon off;'"
        networks:
          - influxdb
    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "./nginx.conf:/etc/nginx/conf.d/default.conf"
          - "./data/vhost:/etc/nginx/vhost.d"
          - "./data/html:/usr/share/nginx/html"
          - "./data/letsencrypt/certs:/etc/nginx/certs:rw" 
        environment:
          NGINX_PROXY_CONTAINER: nginx
        networks:
          - influxdb
    influxdb:
        image: influxdb:latest
        restart: always
        volumes:
          - ./data/influxdb:/var/lib/influxdb
        networks:
          - influxdb
    kapacitor:
        image: kapacitor:latest
        depends_on: [influxdb]
        restart: always
        environment:
          KAPACITOR_HOSTNAME: kapacitor
          KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        volumes:
          - ./data/kapcitor:/var/lib/kapacitor
        networks:
          - influxdb
    chronograf:
        image: chronograf:latest
        depends_on: [influxdb,kapacitor]
        restart: always
        volumes:
          - ./data/chronograf:/var/lib/chronograf
        networks:
          - influxdb
        environment:
          VIRTUAL_HOST: telemetry.functn.com
          LETSENCRYPT_HOST: telemetry.functn.com
          LETSENCRYPT_EMAIL: christoph@functn.com
        command:
          - chronograf
          - --influxdb-url=http://influxdb:8086
    telegraf:
      image: telegraf:latest
      hostname: telegraf
      depends_on: [influxdb,nginx]
      restart: always
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/rootfs/sys:ro
        - /proc:/rootfs/proc:ro
        - /etc:/rootfs/etc:ro
      depends_on: [influxdb]
      environment:
        HOST_PROC: /rootfs/proc
        HOST_SYS: /rootfs/sys
        HOST_ETC: /rootfs/etc
      networks:
          - influxdb

networks:
    influxdb: